{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{include "aws-acm-operator.clusterRoleName" .}}
subjects:
  - kind: ServiceAccount
    name: {{include "aws-acm-operator.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{include "aws-acm-operator.clusterRoleName" .}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}