name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.6.3

    - name: Package Helm chart
      run: helm package charts/aws-acm-operator --destination .

    - name: Upload packaged chart to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        publish_dir: ./ 

    - name: Update Helm repo index
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout gh-pages
        helm repo index . --url https://devopsbyakshay.github.io/aws-acm-operator-helm
        git add .
        git commit -m "Update Helm repo index"
        git push
